version: "3.8"

services:
  ai:
    build:
      context: ./AI
    ports:
      - "5000:5000"
    volumes:
      - ./AI:/app
    environment:
      - TOKENIZERS_PARALLELISM=false

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/geogenius
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./geogenius-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: geogenius
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: