version: "3.8"

services:
  ai:
    build:
      context: ./AI
    ports:
      - "5000:5000"
    volumes:
      - ./AI:/app
    environment:
      - TOKENIZERS_PARALLELISM=false

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/geogeniuslocal
      - DB_USER=postgres
      - DB_PASSWORD=jovana123
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./geogenius-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: geogeniuslocal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jovana123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: